server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8000
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /linn

spring:
  application:
    name: linn
  profiles:
#    active: @profileActive@
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/message
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

feign:
  httpclient:
    hc5:
      enabled: true
    max-connections: 200
    max-connections-per-route: 50

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  mapperPackage: com.limyel.linn.*.dao
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.limyel.linn.*.model.entity
  global-config:
    #数据库相关配置
    db-config:
      id-type: auto
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'NULL'
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

logging:
  config: classpath:logback-linn.xml