spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://192.168.200.214:3307/linn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000